export const actionType = () => {
  return {
    SET_USER: 'SET_USER',
    SET_CHIEF_COMPLAINTS: 'SET_CHIEF_COMPLAINTS',
    SET_DIAGNOSIS: 'SET_DIAGNOSIS',
    SET_PROCEDURE: 'SET_PROCEDURE',
    SET_INVESTIGATION: 'SET_INVESTIGATION',
    SET_ADVICE: 'SET_ADVICE',
    SET_EMERGENCY_INSTRUCTIONS: 'SET_EMERGENCY_INSTRUCTIONS',
    SET_PROGNOSIS: 'SET_PROGNOSIS',
  };
};
