export const actionType = () => {
  return {
    SET_USER: 'SET_USER',

    SET_CHIEF_COMPLAINTS: 'SET_CHIEF_COMPLAINTS',
    SET_EXAMINATIONS: 'SET_EXAMINATIONS',
    SET_DIAGNOSIS: 'SET_DIAGNOSIS',
    SET_MEDICATION: 'SET_MEDICATION',
    SET_PROCEDURE: 'SET_PROCEDURE',
    SET_INVESTIGATION: 'SET_INVESTIGATION',
    SET_ADVICE: 'SET_ADVICE',
    SET_FINDINGS: 'SET_FINDINGS',
    SET_EMERGENCY_INSTRUCTIONS: 'SET_EMERGENCY_INSTRUCTIONS',
    SET_PROGNOSIS: 'SET_PROGNOSIS',
    SET_REFER_TO: 'SET_REFER_TO',
    SET_REFER_BY: 'SET_REFER_By',
    SET_DOCTOR_NOTES: 'SET_DOCTOR_NOTES',
  };
};
